# Generated by Django 3.0 on 2022-03-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220322_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateTimeField(max_length=4)),
                ('quarter', models.DateTimeField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
