# Generated by Django 3.0 on 2022-03-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220323_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzongkhag', models.CharField(choices=[('bumthang', 'Bumthang'), ('chhukha', 'Chhukha'), ('dagana', 'Dagana'), ('gasa', 'Gasa'), ('haa', 'Haa'), ('lhuentse', 'Lhuentse'), ('mongar', 'Mongar'), ('paro', 'Paro'), ('pemagatshel', 'Pemagatshel'), ('punakha', 'Punakha'), ('samdrupjongkhar', 'SamdrupJongkhar'), ('samtse', 'Samtse'), ('sarpang', 'Sarpang'), ('thimphu', 'Thimphu'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'TrashiYangtse'), ('trongsa', 'Trongse'), ('tsirang', 'Tsirang'), ('wangduephodrang', 'WangduePhodrang'), ('zhemgang', 'Zhemgang')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='timeline',
            name='quarter',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='year',
            field=models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2015', max_length=4),
        ),
    ]
