# Generated by Django 3.0 on 2022-03-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220323_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userAgency', models.CharField(max_length=100)),
                ('userType_id', models.IntegerField()),
                ('userDzongkhag', models.CharField(max_length=100)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
